fix: update gitops and quickstart docs
devstream-io/website pull request #31
Opened 2022-05-09 08:20 UTC by lfbdev

update gitops and quickstart docs

2022-05-09 08:26 UTC, daniel-hutao commented on docs/03-Tutorials/02-best-practices/gitops.md
> +[gitops.yaml](https://github.com/devstream-io/devstream/blob/main/examples/gitops.yaml)
- xxx
- yyy
- zzz

2022-05-09 08:27 UTC, daniel-hutao requested changes
See the comment

2022-05-09 08:38 UTC, daniel-hutao approved these changes

2022-05-12 06:36 UTC, IronCore864 commented
We have migrated our documentation back to the main repo (devstream-io/devstream,) so merging this PR won't change anything. Please update the main repo.

2022-05-12 06:36 UTC, closed without merging